# Service configuration
service:
  host: HOST_NAME
  port: SERVICE_PORT
  baseUrl: SERVICE_BASE_URL

# Database configuration
mongodb:
  uri: MONGODB_URI

# API documentation configuration
api-docs:
  username: API_DOCS_USERNAME
  password: API_DOCS_PASSWORD

# Log configuration
log:
  level: LOG_LEVEL
